#!/bin/bash
echo '提示：开始安装parted分区工具'
apt-get install -y parted
echo '提示：parted分区工具安装完成'
fdisk /dev/nvme0n1<./option
echo '提示：扩容物理卷nvme0n1p3'
parted -s /dev/nvme0n1 resizepart 3 100%
echo '提示：更新物理卷到pve卷组'
pvresize /dev/nvme0n1p3
echo '提示：更新逻辑卷'
lvextend -l +100%FREE /dev/pve/root
echo '提示：更新文件系统'
resize2fs /dev/pve/root
echo '提示：最好重启一下哦，输入reboot重启'
